#!/usr/bin/env bash
#
# rescue_label_caches.sh - copy Ultralytics label caches to durable storage, verified.
# Issue #51.
#
# WHY THIS EXISTS
#   /gscratch/scrubbed purges by ACCESS time, and an Ultralytics label cache is precisely
#   what stops anything from reading the individual label .txt files.  Their atime froze
#   while the images kept being read every epoch, so the 2026-08 purge took all 718,415
#   tile labels and left every image.  The cache that made training fast is what got the
#   labels deleted.
#
#   The recovery works because the cache is not a digest: it stores parsed `cls` (n,1)
#   and `bboxes` (n,4) as normalized xywh, which is the on-disk .txt format itself, so
#   rebuild_yolo_labels_from_cache.py can reconstitute the labels exactly.  That makes
#   the cache the single most valuable small file in the dataset -- and it was sitting on
#   the same volume, on the same purge clock, as the thing it is the backup for.
#
#   The tiles pair was staged by hand on 2026-08-17.  A hand-assembled backup cannot be
#   re-run by someone else, which is the test this repo applies to everything else
#   (CLAUDE.md, "replicable from a clean clone").  This is that staging, as a script.
#
# WHAT IT GUARANTEES
#   - Never destroys a good copy: each file lands as <name>.tmp and is renamed only after
#     its hash matches the source.
#   - Idempotent: a destination that already matches is reported unchanged and left alone.
#   - Refuses to overwrite a DIFFERING existing copy unless FORCE=1.  This is deliberate.
#     A cache regenerated by a later Ultralytics run is not the cache the published arms
#     trained on, and silently replacing the durable copy with it would lose the original
#     while looking like a successful backup.
#
# LAYOUT
#   Caches land at $DST/<variant>/{train,val}.cache with sha256sums.txt beside them.
#   The tiles pair already lives FLAT at $DST/{train,val}.cache, which is what
#   run_rebuild_yolo_labels.slurm defaults YOLO_CACHE_DIR to; that legacy path is left
#   exactly as it is.  For any other variant, point YOLO_CACHE_DIR at its subdirectory:
#
#     YOLO_CACHE_DIR=$DST/pano YOLO_DATA_ROOT=$SRC/pano \
#       sbatch scripts/model_comparison/run_rebuild_yolo_labels.slurm
#
# USAGE
#   ./rescue_label_caches.sh                 # every variant under SRC that has caches
#   ./rescue_label_caches.sh pano            # only the named variants
#   SRC=... DST=... ./rescue_label_caches.sh # override the committed defaults
#
set -uo pipefail

SRC="${SRC:-/gscratch/scrubbed/jfroehli/yolo}"
DST="${DST:-/gscratch/makelab/jonf/rampnet_yolo_baseline_51/label_cache_rescue}"
FORCE="${FORCE:-0}"
MAX_TRIES="${MAX_TRIES:-3}"

SPLITS=(train val)

n_copied=0; n_same=0; n_failed=0; n_refused=0

log() { printf '%s\n' "$*"; }

human() { numfmt --to=iec --suffix=B "$1" 2>/dev/null || printf '%s' "$1"; }

# copy_verified <src-file> <dst-file> <label>
copy_verified() {
  local s=$1 d=$2 rel=$3 try=0 h1 h2 hd
  while [ "$try" -lt "$MAX_TRIES" ]; do
    try=$((try + 1))
    h1=$(sha256sum "$s" | cut -d' ' -f1)
    if [ -f "$d" ]; then
      hd=$(sha256sum "$d" | cut -d' ' -f1)
      if [ "$hd" = "$h1" ]; then
        log "     = $rel  ($(human "$(stat -c%s "$s")"))  unchanged"
        n_same=$((n_same + 1))
        return 0
      fi
      if [ "$FORCE" != "1" ]; then
        log "     ! $rel  REFUSED: a DIFFERENT copy already exists at the destination."
        log "         durable ${hd:0:12}...  source ${h1:0:12}..."
        log "         The durable copy is probably the original and the source a later"
        log "         regeneration. Inspect both, then re-run with FORCE=1 if the source"
        log "         really is the one to keep."
        n_refused=$((n_refused + 1))
        return 1
      fi
    fi
    mkdir -p "$(dirname "$d")"
    if ! cp -f "$s" "$d.tmp"; then
      log "     ! $rel  COPY FAILED"
      rm -f "$d.tmp"
      n_failed=$((n_failed + 1))
      return 1
    fi
    # Hash the source again: a cache being rewritten by a live run would otherwise be
    # captured torn, and a torn cache verifies fine against itself.
    h2=$(sha256sum "$s" | cut -d' ' -f1)
    if [ "$h1" != "$h2" ]; then
      rm -f "$d.tmp"
      log "     ~ $rel  source moved mid-copy, retry $try/$MAX_TRIES"
      sleep 10
      continue
    fi
    hd=$(sha256sum "$d.tmp" | cut -d' ' -f1)
    if [ "$hd" != "$h1" ]; then
      rm -f "$d.tmp"
      log "     ! $rel  hash mismatch after copy, retry $try/$MAX_TRIES"
      continue
    fi
    mv -f "$d.tmp" "$d"
    log "     + $rel  ($(human "$(stat -c%s "$d")"))  sha256 ${h1:0:12}..."
    n_copied=$((n_copied + 1))
    return 0
  done
  log "     ! $rel  GAVE UP after $MAX_TRIES tries"
  n_failed=$((n_failed + 1))
  return 1
}

[ -d "$SRC" ] || { log "FATAL: SRC not found: $SRC"; exit 2; }
mkdir -p "$DST" || { log "FATAL: cannot create DST: $DST"; exit 2; }

if [ "$#" -gt 0 ]; then
  variants=("$@")
else
  mapfile -t variants < <(
    cd "$SRC" && for v in */; do
      v=${v%/}
      for s in "${SPLITS[@]}"; do
        [ -f "$v/labels/${s}.cache" ] && { printf '%s\n' "$v"; break; }
      done
    done
  )
fi

log "rescue_label_caches.sh  $(date -u +%Y-%m-%dT%H:%M:%SZ)"
log "  SRC $SRC"
log "  DST $DST"
log "  variants: ${variants[*]:-<none found>}"
log ""

for v in "${variants[@]:-}"; do
  [ -n "$v" ] || continue
  log "== $v"
  found=0
  for s in "${SPLITS[@]}"; do
    src="$SRC/$v/labels/${s}.cache"
    if [ ! -f "$src" ]; then
      log "     - $v/${s}.cache (absent at source)"
      continue
    fi
    found=1
    copy_verified "$src" "$DST/$v/${s}.cache" "$v/${s}.cache"
  done
  [ "$found" = "1" ] || { log "     (no caches for this variant)"; continue; }

  # Checksums beside the caches, in the format run_rebuild_yolo_labels.slurm checks
  # with `cd "$CACHE_DIR" && sha256sum -c sha256sums.txt`.
  if [ -d "$DST/$v" ]; then
    ( cd "$DST/$v" && sha256sum ./*.cache 2>/dev/null | sed 's#\./##' >sha256sums.txt )
    log "     sha256sums.txt written ($(wc -l <"$DST/$v/sha256sums.txt") entries)"
  fi
  log ""
done

log "copied $n_copied, unchanged $n_same, refused $n_refused, failed $n_failed"
log ""
log "Verify any time with:  cd $DST/<variant> && sha256sum -c sha256sums.txt"
[ "$n_failed" -eq 0 ] && [ "$n_refused" -eq 0 ] || exit 1
